
export const fakeData =[
    {
      TconsultationId : null,
      antecedents : "bronchite",
      commentaire : null,
      createdAt : "2024-06-21T19:36:53.000Z",
      date_debut: null,
      date_fin: null,
      diagnostique: null,
      employeId: null,
      height: 14,
      id: 1,
      matricule : "202406211",
      patientID : null,
      prescription : null,
      pressure: 5,
      statut: "EnAttente",
      symptomes: "mal de dos",
      temperature: 12,
      updatedAt : "2024-06-22T01:56:02.000Z",
      weight : 56,
    
      firstName: 'Kelvin',
      lastName: 'Langosh',
      birthDate: '18',
      sex: 'M',
    },
    {
    
      TconsultationId :  null,
      adress  :   null,
      antecedents  :   null,
      birthDate  :  "1924-02-12T00:00:00.000Z",
      cni  :  null,
      commentaire  :   null,
      createdAt  :  "2024-06-22T05:54:33.000Z",
      date_debut  :  null,
      date_fin : null,
      diagnostique  :   null,
      email  :   null,
      employeId  : null,
      firstName  :   "william",
      height  :   null,
      id  :   1,
      lastName  :   "well",
      matricule  :  "202406221",
      patientId  :   null,
      prescription  :   null,
      pressure  :   null,
      sex :   "M",
      statut  :   "EnAttente",
      symptomes  :   null,
      tel  :   null,
      temperature  : null,
      updatedAt  :   "2024-06-22T05:54:33.000Z",
      weight  :  null,
    },
      {
        matricule: '9s41rp',
        firstName: 'Kelvin',
        lastName: 'Langosh',
        birthDate: '18',
        sex: 'M',
        temperature: "15",
        weight : "80",
        pressure : "15",
        symptomes : "Céphalées",
        antecedents : "Diabète, hypertension",
        diagnostique : "",
        prescription : ""
      },
      {
        matricule: '08m6rx',
        firstName: 'Molly',
        lastName: 'Purdy',
        birthDate: '18',
        sex: 'M',
        temperature: "15",
        weight : "80",
        pressure : "15",
        symptomes : "Céphalées",
        antecedents : "Diabète, hypertension",
        diagnostique : "Diarhée",
        prescription : "Malacur"
      },
      {
        matricule: '5ymtrc',
        firstName: 'Henry',
        lastName: 'Lynch',
        birthDate: '18',
        sex: 'M',
        temperature: "15",
        weight : "80",
        pressure : "15",
        symptomes : "Céphalées",
        antecedents : "Diabète, hypertension",
        diagnostique : "Diarhée",
        prescription : "Malacur"
      },
      {
        matricule: 'ek5b97',
        firstName: 'Glenda',
        lastName: 'Douglas',
        birthDate: '18',
        sex: 'M',
        temperature: "15",
        weight : "80",
        pressure : "15",
        symptomes : "Céphalées",
        antecedents : "Diabète, hypertension",
        diagnostique : "",
        prescription : ""
      },
      {
        matricule: 'xxtydd',
        firstName: 'Leone',
        lastName: 'Williamson',
        birthDate: '18',
        sex: 'M',
        temperature: "15",
        weight : "80",
        pressure : "15",
        symptomes : "Céphalées",
        antecedents : "Diabète, hypertension",
        diagnostique : "",
        prescription : ""
      },
      {
        matricule: 'wzxj9m',
        firstName: 'Mckenna',
        lastName: 'Friesen',
        birthDate: '18',
        sex: 'M',
        temperature: "15",
        weight : "80",
        pressure : "15",
        symptomes : "Céphalées",
        antecedents : "Diabète, hypertension",
        diagnostique : "Diarhée",
        prescription : "Malacur"
      },
      {
        matricule: '21dwtz',
        firstName: 'Wyman',
        lastName: 'Jast',
        birthDate: '18',
        sex: 'M',
        temperature: "15",
        weight : "80",
        pressure : "15",
        symptomes : "Céphalées",
        antecedents : "Diabète, hypertension",
        diagnostique : "Diarhée",
        prescription : "Malacur"
      },
      {
        matricule: '21dwtz',
        firstName: 'Wyman',
        lastName: 'sdfsdf',
        birthDate: '18',
        sex: 'M',
        temperature: "15",
        weight : "80",
        pressure : "15",
        symptomes : "Céphalées",
        antecedents : "Diabète, hypertension",
        diagnostique : "",
        prescription : ""
      },
      {
        matricule: 'o8oe4k',
        firstName: 'Janick',
        lastName: 'Willms',
        birthDate: '18',
        sex: 'M',
        temperature: "15",
        weight : "80",
        pressure : "15",
        symptomes : "Céphalées",
        antecedents : "Diabète, hypertension",
        diagnostique : "",
        prescription : ""
      },
    ];