
export const fakeData =[
  {
    patientId: '9s41rp',
    firstName: 'Kelvin',
    lastName: 'Langosh',
    birthDate: '2016-02-23T18:25:43.511Z',
    gender: 'Jerod14@hotmail.com',
    gender1: 'Jerod14@hotmail.com',
    service: 'Ohio',
  },
  {
    patientId: '08m6rx',
    firstName: 'Molly',
    lastName: 'Purdy',
    birthDate: '2016-02-23T18:25:43.511Z',
    gender: 'Hugh.Dach79@hotmail.com',
    gender1: 'Hugh.Dach79@hotmail.com',
    service: 'Rhode Island',
  },
  {
    patientId: '5ymtrc',
    firstName: 'Henry',
    lastName: 'Lynch',
    birthDate: '2019-02-23T18:21:43.335',
    gender: 'Camden.Macejkovic@yahoo.com',
    gender1: 'Camden.Macejkovic@yahoo.com',
    service: 'California',
  },
  {
    patientId: 'ek5b97',
    firstName: 'Glenda',
    lastName: 'Douglas',
    birthDate: '2019-02-23T18:21:43.335',
    gender: 'Eric0@yahoo.com',
    gender1: 'Eric0@yahoo.com',
    service: 'Montana',
  },
  {
    patientId: 'xxtydd',
    firstName: 'Leone',
    lastName: 'Williamson',
    birthDate: '2015-02-25T18:25:43.511Z',
    gender: 'Ericka_Mueller52@yahoo.com',
    gender1: 'Ericka_Mueller52@yahoo.com',
    service: 'Colorado',
  },
  {
    patientId: 'wzxj9m',
    firstName: 'Mckenna',
    lastName: 'Friesen',
    birthDate: '2023-06-11T18:25:43.511Z',
    gender: 'Veda_Feeney@yahoo.com',
    gender1: 'Veda_Feeney@yahoo.com',
    service: 'New York',
  },
  {
    patientId: '21dwtz',
    firstName: 'Wyman',
    lastName: 'Jast',
    birthDate: '2019-02-23T18:21:43.335',
    gender: 'Melvin.Pacocha@yahoo.com',
    gender1: 'Melvin.Pacocha@yahoo.com',
    service: 'Montana',
  },
  {
    patientId: 'o8oe4k',
    firstName: 'Janick',
    lastName: 'Willms',
    birthDate: '2019-02-23T18:21:43.335',
    gender: 'Delfina12@gmail.com',
    gender1: 'Delfina12@gmail.com',
    service: 'Nebraska',
  },
];

//50 us services array
export const serviceStates = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'Puerto Rico',
];
